In [11]:
import duckdb
import pandas as pd
con = duckdb.connect("funnel.duckdb")

In [12]:
con.sql("SELECT * FROM accounts LIMIT 5").df()

,account_id,company,segment,industry,country
0,1,"Rodriguez, Figueroa and Sanchez",midmarket,Logistics,USA
1,2,Doyle Ltd,startup,Healthcare,Germany
2,3,"Mcclain, Miller and Henderson",midmarket,Logistics,Germany
3,4,Davis and Sons,midmarket,Manufacturing,UK
4,5,"Guzman, Hoffman and Baldwin",startup,Retail,USA

In [17]:
con.sql("SELECT segment, COUNT(*) AS companies FROM accounts GROUP BY segment ORDER BY companies DESC").df()

      segment  companies
0     startup        361
1   midmarket        184
2  enterprise         55

In [ ]:
##-Query 1

con.sql("""
SELECT a.segment,
       COUNT(*) AS leads,
       COUNT(d.deal_id) AS deals,
       COUNT(CASE WHEN d.status = 'won' THEN 1 END) AS won
FROM leads l
JOIN accounts a ON a.account_id = l.account_id
LEFT JOIN deals d ON d.account_id = l.account_id
GROUP BY a.segment
ORDER BY leads DESC
""").df()

      segment  leads  deals  won
0     startup    361    227  102
1   midmarket    184    109   52
2  enterprise     55     44   12

In [24]:
##-Query 2

con.sql("""
SELECT a.segment,
       COUNT(*) AS leads,
       COUNT(d.deal_id) AS deals,
       COUNT(CASE WHEN d.status = 'won' THEN 1 END) AS won
       ROUND(100.0 * deals / leads, 2) AS pct_leads_to_deal,
       ROUND(100.0 * COUNT(d.deal_id) / NULLIF(COUNT(*), 0), 2) AS pct_deals_won
FROM leads l
JOIN accounts a ON a.account_id = l.account_id
LEFT JOIN deals d ON d.account_id = l.account_id
GROUP BY a.segment
ORDER BY leads DESC
""").df()

ParserException: Parser Error: syntax error at or near "ROUND"

LINE 6:        ROUND(100.0 * deals / leads, 2) AS pct_leads_to_deal,
               ^